import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "../lib/providers";
import { ReduxProvider } from "@/store/provider";
import "@ant-design/v5-patch-for-react-19";
import { Toaster } from "@/components/ui/sonner";
import { AuthGuard } from "@/components/UnauthorizedDialog";
import ClientLayoutWrapper from "./layoutWrapper";
import "@/shared/utils/suppressAntdFormWarning";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/airbnb-1.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <AppProviders>
          <ReduxProvider>
            <AuthGuard>
              <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
            </AuthGuard>
          </ReduxProvider>
          <Toaster duration={3000} richColors position="top-right" />
        </AppProviders>
      </body>
    </html>
  );
}
